### ISSUE TITLE
Version gate clients and servers separately

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/Atlas#27]
We should split up the version gate for servers and clients.

In particular in our current setup, updating a client is much easier than a server (assuming mod-manager). At the same time most vulnerabilities we had to patch and version gate for were on client. As such, we should selectively version gate so that we don't force servers to update where they don't have to.

Another use-case is changes that break backwards compatibility. For example, https://github.com/R2Northstar/NorthstarLauncher/pull/408 will break compatibility with old clients when joining newer servers but newer clients can still play on old servers. As such, it would make sense to version gate only client here.

**Comment by pg9182** [comment]
If nobody else wants to try implementing this, I'll do it sometime in the next few days.
